### ISSUE TITLE
Document if the position within `INSTALLED_APPS` is significant

### ISSUE THREAD

**Issue by johnthagen** [YegorDB/django-channels-auth-token-middlewares#2]
In the user guide it states:

> Add app name to `INSTALLED_APPS`

```py
INSTALLED_APPS = [
    ...
    'channels_auth_token_middlewares',
]
```

Often times the order of where middleware is placed is significant. Could the README be updated to either say that the order does not matter, or if there are any dependency orders (such as needing to come before/after another standard middleware) to add those?

**Comment by YegorDB** [comment]
Good idea.
