### ISSUE TITLE
`SimpleJWTAuthTokenMiddleware` fails to parse Authorization header correctly

### ISSUE THREAD

**Issue by johnthagen** [YegorDB/django-channels-auth-token-middlewares#3]
The following code snippet demonstrates an issue with `SimpleJWTAuthTokenMiddleware` that it does not properly check the `header_name` because `HeaderAuthTokenMiddleware` lowers the string:

https://github.com/YegorDB/django-channels-auth-token-middlewares/blob/9c366047f04987d0f4c9db45f1bd6e6f669fc238/channels_auth_token_middlewares/middleware/base.py#L105

The code below will not set the `self.scope["user"]` for an `AsyncJsonWebsocketConsumer` in the `connect()` method.

```py
# asgi.py
application = ProtocolTypeRouter(
    {
        "http": django_asgi_app,
        "websocket": AllowedHostsOriginValidator(
            SimpleJWTAuthTokenMiddleware(
                URLRouter(...),
            ),
        ),
    }
)
```

```py
# unit tests
from channels.db import database_sync_to_async
from channels.testing import WebsocketCommunicator
from channels_auth_token_middlewares.middleware import SimpleJWTAuthTokenMiddleware
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import pytest
from rest_framework_simplejwt.tokens import AccessToken

from config.asgi import application


@database_sync_to_async
def create_user(username: str, password: str) -> tuple[User, AccessToken]:
    user = get_user_model().objects.create_user(username=username, password=password)
    access = AccessToken.for_user(user)
    return user, access


def generate_auth_headers(access_token: AccessToken) -> list[tuple[bytes, bytes]]:
    return [
        (
            SimpleJWTAuthTokenMiddleware.header_name.encode(),
            f"{SimpleJWTAuthTokenMiddleware.keyword} {access_token}".encode(),
        )
    ]


@pytest.mark.asyncio
@pytest.mark.django_db
async def test_connect() -> None:
    _, access_token = await create_user("user", "password")

    communicator = WebsocketCommunicator(
        application,
        f"my-url/",
        headers=generate_auth_headers(access_token),
    )
    is_connected, _ = await communicator.connect()
```

This is because the header is sent as `b'Authorization'`, but `HeaderAuthTokenMiddleware` lowers this to `b'authorization'`, thus `get_token_key_string()` does not pull the token `value` out correctly and instead returns `None`:

https://github.com/YegorDB/django-channels-auth-token-middlewares/blob/9c366047f04987d0f4c9db45f1bd6e6f669fc238/channels_auth_token_middlewares/middleware/base.py#L111-L116

In my own test code, if I `lower()` the header name, it works but this isn't how a browser client would send the header:

```py
def generate_auth_headers(access_token: AccessToken) -> list[tuple[bytes, bytes]]:
    return [
        (
            # Temporary hack to lower header name to show that this is the issue.
            SimpleJWTAuthTokenMiddleware.header_name.lower().encode(),
            f"{SimpleJWTAuthTokenMiddleware.keyword} {access_token}".encode(),
        )
    ]
```

**Comment by johnthagen** [comment]
@YegorDB Any reason to `lower()` the `header_name` within `HeaderAuthTokenMiddleware`? I'd be happy to open a PR to remove this, but wanted to check if there was a specific, intentional reason for this first.

**Comment by YegorDB** [comment]
When I was writing and testing that middlewares, scope headers always was in lower case.
But in ASGI docs [scope section](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope) written "Header names should be lowercased, but it is not required".
So [this commit](https://github.com/YegorDB/django-channels-auth-token-middlewares/commit/3ead720c05b20b7e7d6a84dd11a820d39dde2742) should solve your problem, @johnthagen.
In couple days I will make new package release.

**Comment by johnthagen** [comment]
> "Header names should be lowercased, but it is not required".

That is very interesting. Perhaps this is due to a side effect of how the `Communicator` works within the ASGI stack and if a _real_ client sent in the `Authorization` header, then somewhere in the stack (at uvicorn/daphne or lower?) it would be lower-cased.

Like you said, I think it's still best to preserve it anyway.
