### ISSUE TITLE
Add automated unit test suite

### ISSUE THREAD

**Issue by johnthagen** [YegorDB/django-channels-auth-token-middlewares#4]
One way to help ensure the quality of the project would be to add a few unit tests for each of the middleware solutions in the project.

Django Channels has some good documentation on how to test channels application using `pytest`, `pytest-asyncio`, and the `channels` testing `Communicator`s:

- https://channels.readthedocs.io/en/stable/topics/testing.html
- https://channels.readthedocs.io/en/stable/tutorial/part_4.html

I think the way this could be done would be by writing one or more very simple `Consumer`s that exercise the middleware and assert that connections are established correctly when the various middleware solutions are in use.

One such example is listed in the comment here:

- https://github.com/YegorDB/django-channels-auth-token-middlewares/issues/3#issue-1666738223

These unit tests could then be automated to run against all versions of Python that the library supports. There are many ways to do this, one example would be to use [Nox](https://nox.thea.codes/en/stable/) and [GitHub Actions](https://docs.github.com/en/actions). An example project that shows examples of how this could be done (also using Poetry, which is optional):

- https://github.com/johnthagen/python-blueprint/blob/master/noxfile.py#L13
- https://github.com/johnthagen/python-blueprint/blob/master/.github/workflows/python.yml#L10

**Comment by YegorDB** [comment]
Thanks for another good idea to improve project!

**Comment by johnthagen** [comment]
Tests added in

- #6
